backend:
  name: github
  repo: americool/phenomic-netlify-CMS-test
  branch: master

public_folder: "/assets"
media_folder: "content/assets"

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    sort: "date:desc" # Default is title:asc
    slug: "{{slug}}"
    card: {type: "alltype", text: "title"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image", optional: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "string", default: "Post"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - name: "general"
        label: "General settings"
        file: "_settings/general.json"
        fields:
          - {label: "Main site title", name: "site_title", widget: "string"}
          - {label: "Number of frontpage posts", name: "post_count", widget: "number"}
          - {label: "Site cover image", name: "cover", widget: "image"}

      - name: "config"
        label: "Backend"
        file: "admin/config.yml"
        description: "Backend Editor"
        fields:
          - name: backend
            label: Backend
            widget: "object"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Repo", name: "repo", widget: "string"}
              - {label: "Branch", name: "branch", widget: "string"}

      - name: "extraSettings"
        label: "Config Settings"
        file: "admin/config.yml"
        description: "publishMode & media_folder"
        fields:
          - name: extrasettings
            label: More Settings
            widget: "object"
            fields:
              - {label: "Publish Mode", name: "publish_mode", widget: "string"}
              - {label: "Media Folder", name: "media", widget: "string"}
