backend:
  branch: master
  name: github
  repo: americool/phenomic-netlify-CMS-test
collections:
  - card:
      text: title
      type: alltype
    create: 'false'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Cover
        name: cover
        optional: true
        widget: image
      - label: Body
        name: body
        widget: markdown
      - default: Post
        label: Layout
        name: layout
        widget: string
      - format: YYYY-MM-DD
        label: Publish Date
        name: date
        widget: datetime
    folder: content/posts
    label: Post
    name: post
    slug: '{{slug}}'
    sort: 'date:desc'
  - editor:
      preview: false
    files:
      - fields:
          - label: Main site title
            name: site_title
            widget: string
          - label: Number of frontpage posts
            name: post_count
            widget: number
          - label: Site cover image
            name: cover
            widget: image
        file: _settings/general.json
        label: General settings
        name: general
      - description: Backend Editor
        fields:
          - fields:
              - label: Name
                name: name
                widget: string
              - label: Repo
                name: repo
                widget: string
              - label: Branch
                name: branch
                widget: string
            label: Backend
            name: backend
            widget: object
          - fields:
              - label: Publish Mode
                name: publish_mode
                widget: string
              - label: Public Folder
                name: public_folder
                widget: string
              - label: Media Folder
                name: media_folder
                widget: string
            label: Config
            name: Other
            widget: object
          - fields:
              - label: Name
                name: name
                widget: string
              - label: Label
                name: label
                widget: string
              - label: Folder
                name: folder
                widget: string
              - label: Create
                name: create
                widget: string
              - label: Sort
                name: sort
                widget: string
              - label: Slug
                name: slug
                widget: string
              - label: Fields
                name: fields
                widget: list
            label: Collections
            name: collections
            widget: list
        file: admin/config.yml
        label: Config
        name: config
    label: Settings
    name: settings
media_folder: content/assets
public_folder: /assets
publish_mode: editorial_workflow
